{
 "title": "Job DashBoard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "BackendGroup",
    "query": "select distinct name from moreh_master.BackendGroup"
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "moreh_master",
     "rawSql": "SELECT coalesce(sum(device_count), 0) as AvailableDevices\nFROM ( SELECT \n    Backend.id as be_id, count(Device.id) as device_count\n  FROM Device\n  LEFT JOIN DeviceStatus ON Device.stat_id = DeviceStatus.id\n  LEFT JOIN Backend on Device.be_id = Backend.id\n  LEFT JOIN BackendStatus ON BackendStatus.id = Backend.stat_id\n  LEFT JOIN BackendGroup ON Backend.group_id = BackendGroup.id\n  WHERE\n    BackendStatus.status in (\"ACTIVE\") and DeviceStatus.status = \"IDLE\" and BackendGroup.name in ($BackendGroup)\n  GROUP BY Backend.id\n) AS A"
    },
    {
     "dataset": "moreh_master",
     "rawSql": " SELECT \n    coalesce(count(distinct Device.id), 0) as RunningDevices\n  FROM Device\n  LEFT JOIN DeviceStatus ON Device.stat_id = DeviceStatus.id\n  LEFT JOIN Backend on Device.be_id = Backend.id\n  LEFT JOIN BackendStatus ON BackendStatus.id = Backend.stat_id\n  LEFT JOIN BackendGroup ON Backend.group_id = BackendGroup.id\n  WHERE\n    BackendStatus.status in (\"ACTIVE\") and DeviceStatus.status = \"PROCESSING\" and BackendGroup.name in ($BackendGroup)"
    },
    {
     "dataset": "moreh_master",
     "rawSql": "  select coalesce(sum(nodes_count), 0) * 8 as ShutDownDevices\n  from (\n    select BackNode, status, case when sum(nodes) > 1 then 1 else sum(nodes) end as nodes_count\n    from (\n      SELECT distinct concat(\"back\", LPAD(be_id, 3, '0')) as BackNode,\n      Device.idx, 0.125 as nodes, status\n      FROM Device\n      LEFT JOIN DeviceStatus ON Device.stat_id = DeviceStatus.id\n      LEFT JOIN Backend ON Device.be_id = Backend.id\n      LEFT JOIN BackendGroup ON Backend.group_id = BackendGroup.id\n      WHERE BackendGroup.name in ($BackendGroup)) as A\n    group by 1,2\n    having status = 'SHUTDOWN'\n    UNION\n    select distinct host as BackNode, status, 1 as nodes_count\n    from Backend\n    LEFT JOIN BackendStatus ON Backend.stat_id = BackendStatus.id\n    LEFT JOIN BackendGroup ON Backend.group_id = BackendGroup.id\n    where status = 'SHUTDOWN' and BackendGroup.name in ($BackendGroup)) as B\n"
    }
   ]
  },
  {
   "title": "Running Jobs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "moreh_master",
     "rawSql": "SELECT count(distinct fe_id) as CountRunningJob\nFROM JobQueue\nLEFT JOIN JobStatus ON JobStatus.id = JobQueue.stat_id\nWHERE\n  status in (\"RUNNING\")"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "moreh_master",
     "rawSql": "SELECT coalesce(sum(CASE WHEN device_count >= 8 THEN 1 ELSE 0 END), 0) as StandbyNodes\nFROM ( SELECT \n    Backend.id as be_id, count(Device.id) as device_count\n  FROM Device\n  LEFT JOIN DeviceStatus ON Device.stat_id = DeviceStatus.id\n  LEFT JOIN Backend on Device.be_id = Backend.id\n  LEFT JOIN BackendStatus ON BackendStatus.id = Backend.stat_id\n  LEFT JOIN BackendGroup ON Backend.group_id = BackendGroup.id\n  WHERE\n    BackendStatus.status in (\"ACTIVE\") and DeviceStatus.status = \"IDLE\" and BackendGroup.name in ($BackendGroup)\n  GROUP BY Backend.id\n) AS A"
    },
    {
     "dataset": "moreh_master",
     "rawSql": " SELECT \n    coalesce(count(distinct Backend.id), 0) as RunningNodes\n  FROM Device\n  LEFT JOIN DeviceStatus ON Device.stat_id = DeviceStatus.id\n  LEFT JOIN Backend on Device.be_id = Backend.id\n  LEFT JOIN BackendStatus ON BackendStatus.id = Backend.stat_id\n  LEFT JOIN BackendGroup ON Backend.group_id = BackendGroup.id\n  WHERE\n    BackendStatus.status in (\"ACTIVE\") and DeviceStatus.status = \"PROCESSING\" and BackendGroup.name in ($BackendGroup)"
    },
    {
     "dataset": "moreh_master",
     "rawSql": "  SELECT \n    coalesce(count(distinct Backend.id), 0) as ShutDownNodes\n  FROM Device\n  LEFT JOIN DeviceStatus ON Device.stat_id = DeviceStatus.id\n  LEFT JOIN Backend on Device.be_id = Backend.id\n  LEFT JOIN BackendStatus ON BackendStatus.id = Backend.stat_id\n  LEFT JOIN BackendGroup ON Backend.group_id = BackendGroup.id\n  WHERE\n    (BackendStatus.status in (\"SHUTDOWN\") and BackendGroup.name in ($BackendGroup)) OR  (DeviceStatus.status = \"SHUTDOWN\" and BackendGroup.name in ($BackendGroup))"
    }
   ]
  },
  {
   "title": "Queued Jobs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "moreh_master",
     "rawSql": "SELECT count(distinct fe_id) as QueuedJob\nFROM JobQueue\nLEFT JOIN JobStatus ON JobStatus.id = JobQueue.stat_id\nWHERE\n  status in (\"QUEUED\", \"SUBMITTED\", \"NOT_ENOUGH_GPU\")"
    }
   ]
  },
  {
   "title": "Job List",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "dataset": "moreh_master",
     "rawSql": "SELECT distinct\n  JobStatus.status as status,\n  JobQueue.fe_id,\n  Token.name as TokenName,\n  Token.value as TokenValue,\n  timestampdiff(MINUTE, start_time, NOW()) as RunningTime,\n  timestampdiff(SECOND, JobHeartbeat.heartbeat, NOW()) as Heartbeat,\n  version as \"ver\",\n  client_info as \"framework\",\n  proc_name as process,\n  device_count / 8 as node_count,\n  SDAModel.name as SDAModel,\n  start_time,\n  request_time,\n  REPLACE(group_concat(distinct Backend.host order by cast(REPLACE(Backend.host, \"mi250-\", \"\") as integer) ), \"mi250-\", \"\") as Backnode\nFROM JobQueue\nLEFT JOIN Device ON Device.fe_id = JobQueue.fe_id\nLEFT JOIN SDA ON JobQueue.sda_id = SDA.id\nLEFT JOIN Token ON SDA.tok_id = Token.id\nLEFT JOIN Backend on Device.be_id = Backend.id\nLEFT JOIN JobStatus ON JobStatus.id = JobQueue.stat_id\nLEFT JOIN SDAModel ON JobQueue.device_count = SDAModel.devices\nLEFT JOIN JobHeartbeat ON JobQueue.fe_id = JobHeartbeat.fe_id\ngroup by start_time, request_time, version, fe_id, TokenName, heartbeat, status, device_count, SDAModel, client_info\nORDER BY status, start_time desc"
    }
   ]
  },
  {
   "title": "BackNode Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "moreh_master",
     "rawSql": "SELECT CONCAT(Backend.id, REPLACE(BackendGroup.name, 'default_backend_group', ''), ' ', BackendStatus.status, ' ',\n              COUNT(IF(DeviceStatus.status = \"PROCESSING\" OR DeviceStatus.status = \"PREPARING\" OR DeviceStatus.status = \"CLEANING\"  , 1, NULL)), ' ',\n              COUNT(IF(DeviceStatus.status = \"IDLE\", 1, NULL)), ' ',\n              COUNT(IF(DeviceStatus.status = \"SHUTDOWN\", 1, NULL))\n              )\nFROM Backend\nINNER JOIN BackendStatus ON Backend.stat_id = BackendStatus.id\nINNER JOIN Device ON Backend.id = Device.be_id\nINNER JOIN DeviceStatus ON Device.stat_id = DeviceStatus.id\nINNER JOIN BackendGroup ON BackendGroup.id = Backend.group_id\nWHERE BackendGroup.name in ($BackendGroup)\nGROUP BY Backend.id, BackendStatus.status"
    }
   ]
  }
 ]
}